import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  title,
}: Readonly<{
  children: React.ReactNode;
  title: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 p-6 bg-pink-400 flex justify-between items-center">
          {title}
          <nav className="flex gap-4">
            <Link href="/">Home</Link>
            <Link href="/other">Other</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
